### ISSUE TITLE
Not Working With Synapse 3

### ISSUE THREAD

**Issue by liljohn360** [nicojeske/RazerAmbilight#15]
The app doesn't seem to work when using Razer Synapse 3. The tray app opens but the keyboard remains unchanged. Tested with Blackwidow Chroma TE v2 and Deathadder Elite on latest version 1.6.2

Chroma Connect is installed but Ambilight does not show up in the app list.

**Comment by nicojeske** [comment]
Please update to version [1.6.5](https://github.com/nicojeske/RazerAmbilight/releases/download/1.6.5/RazerAmbilight_1_6_5.msi) and try again. If the error consists, please upload the log file located in C:\Users\yourusername\AppData\Roaming\RazerAmbilight\Logs

**Comment by themandalee** [comment]
[2019-01-30.log](https://github.com/nicojeske/RazerAmbilight/files/2815418/2019-01-30.log)

I can't get mine to work out. Here's my log :)

**Comment by liljohn360** [comment]
Same issue unfortunately. 
[2019-01-31.log](https://github.com/nicojeske/RazerAmbilight/files/2816644/2019-01-31.log)

Some more information if needed:
Synapse Version: 3.4.131.12521
Windows Version: Win 10 Home 1809 (Build 17763.292)

**Comment by nicojeske** [comment]
> Same issue unfortunately.
> [2019-01-31.log](https://github.com/nicojeske/RazerAmbilight/files/2816644/2019-01-31.log)
> 
> Some more information if needed:
> Synapse Version: 3.4.131.12521
> Windows Version: Win 10 Home 1809 (Build 17763.292)

Interesting. Unlike @themandalee , there is no error in the log that is thrown by the software. Please try to reinstall Synapse once, this might solve the problem.

**Comment by liljohn360** [comment]
Re-installing Synapse has fixed this problem for me, many thanks! Looks great!

**Comment by nicojeske** [comment]
@themandalee Please update to version 2.0. where I completly rewrote the screen capture method. With this I will close this Issue. If the problem should persist, please open a new issue.
