### ISSUE TITLE
AV false positive

### ISSUE THREAD

**Issue by Tardis50** [nicojeske/RazerAmbilight#17]
Attempting to install Ambilight triggers a (Kaspersky) AV false positive classifying the program and the installer as a trojan.

**Comment by nicojeske** [comment]
Well, that's weird. Scanning the installer with [Virustotal](https://www.virustotal.com/de/file/2e98cd50ac6b2206d71ac6f7465c8b08ee36184e213847b7470541730decb638/analysis/1548949726/) shows negative for all possible virus scanners (including Kaspersky).

**Comment by nicojeske** [comment]
@Tardis50 Please send a screenshot of Kaspersky claiming the program as a false positive so I can further look into it.

**Comment by nicojeske** [comment]
Virustotal does not find a positive Result for neither the installer nor the application itself. So will close the issue for now.
