### ISSUE TITLE
Updated to 2.0 Still nothin :(

### ISSUE THREAD

**Issue by themandalee** [nicojeske/RazerAmbilight#20]
No new logs recorded since 3/3
Looked in here:
C:\Users\Me\AppData\Roaming\RazerAmbilight\Logs

Synapse was reinstalled
Synapse 3.4.216.21216

Razer Blackwidow X Chroma
Razer Lancehead TE

**Comment by nicojeske** [comment]
The fact that no log files are created makes me think that the program doesn't start at all. Does the icon show up in the tray on the taskbar? And just for safety, make sure you have [.Net Framework 4.6.2](https://dotnet.microsoft.com/download/dotnet-framework-runtime/net462) installed.
If that does not help, I'm sorry to say that I currently have no clue what is causing the bug.

**Comment by themandalee** [comment]
Program is open and I made sure I had the .Net Framework 4.6.2 installed

Guess we'll never know why it won't work on mine :(

![amblightNoLogs](https://user-images.githubusercontent.com/46036628/54318483-b9297b00-45a3-11e9-9f4b-a962ec369f63.JPG)

**Comment by themandalee** [comment]
Version 2.0.3 worked for making logs!! Here's mine attached now. Maybe we can get to the bottom of it this time :)
[2019-03-27.log](https://github.com/nicojeske/RazerAmbilight/files/3015754/2019-03-27.log)

**Comment by nicojeske** [comment]
Looking into your looks the software unfortunaly does not throw any error :(. The Desktop Capture even reports, that the screen capture proccess works fine and more then enough frames are captured. As this is the most bug prone part of the software this let's me think that there is some problem with Synapse, the communication with the device etc. 

Are you sure, that the app is enabled in Synapse like this? 
![synapse](https://user-images.githubusercontent.com/17299108/55121597-80d58100-50fb-11e9-84f4-d4daa27dd152.PNG)

Does other software like the [Audio Visualizer from Deleted member 20](https://insider.razer.com/index.php?threads/rock-your-razer-chroma-devices-with-the-audio-visualizer.8796/) work as expected?

**Comment by themandalee** [comment]
It isn't in the apps menu. There's another one with the same name that doesn't work and is outdated but I don't know how to remove it. And I don't know how to add yours. This is probably my roadblock right here.
![connectAppsRazerSynapse](https://user-images.githubusercontent.com/46036628/55122234-6a0f3a00-50bb-11e9-857e-73a95ec6e3c1.JPG)

**Comment by nicojeske** [comment]
I am sorry to say that, but I am really out of ideas for this problem. The program returns no error message so there should be no problem in capturing the screen but rather, as it is seen by the software not shown in the apps list, the problem seems to be in the communication with Synapse or even with Synapse itself... :(

**Comment by themandalee** [comment]
I tried to look up how to add apps to Synapse but turned up with nothing. Does it just automatically add it normally? I think mine is an edge case because I don't know how to add or remove apps.

**Comment by nicojeske** [comment]
You can't add apps manually. Normally it would add the app as it first trys to communicate with the Razer SDK. In other words it should have been added when you first tryed to start the software.

**Comment by themandalee** [comment]
I uninstalled/reinstalled Synapse and opened the Ambilight again but this time it did the old thing where it opened and then closed right away. Uninstalled/reinstalled Ambilight but same result. I guess I made it worse.

**Comment by themandalee** [comment]
[2019-04-03.log](https://github.com/nicojeske/RazerAmbilight/files/3041056/2019-04-03.log)

**Comment by themandalee** [comment]
UPDATE: Instead of uninstall-reinstall for Synapse, I picked repair and now I'm closer than ever. Ambilight finally shows up in the Connect>Apps menu!! Right now the mouse light color is changing around but the keyboard has no light at all.

**Comment by nicojeske** [comment]
It is good to hear that it finally worked for you, at least for some time. Did you try to reinstall Ambilight? This will reset your settings to default.

**Comment by themandalee** [comment]
Yes I reinstalled both Ambilight and Synapse and did the repair thing again.

**Comment by nicojeske** [comment]
And it does not work once again? Currently i think there is some problem with windows overall in your case. As you are the only one with such a problem i don't think the problem is located in the software.

**Comment by themandalee** [comment]
You're probably right. Does this log say anything we can use?
[2019-04-06.log](https://github.com/nicojeske/RazerAmbilight/files/3051094/2019-04-06.log)

**Comment by themandalee** [comment]
Also this is the log from the day it worked.
[2019-04-03.log](https://github.com/nicojeske/RazerAmbilight/files/3051096/2019-04-03.log)

**Comment by themandalee** [comment]
Deleting C:\Users\Manda\AppData\Local\Ambilight made it immediately work again. xD
Just logging all this for if anyone in the future has silly user errors like I did.

**Comment by nicojeske** [comment]
Well that's weird for sure ^^. But I am glad to hear that it finally works :)
