### ISSUE TITLE
Screen not reflected accurately on 2.0

### ISSUE THREAD

**Issue by ruvaldak** [nicojeske/RazerAmbilight#22]
Screen doesn't seem to be reflected as accurately as versions below 2.0. my wallpaper has a big white object on the bottom left that was usually reflected onto my Blackwidow Chroma V2. Version 2.0 does not catch this part, and instead is red like the rest of the wallpaper. It seems a good portion is cut off on the right side and possibly the bottom

Worth noting my keyboard is the default 22x6

**Comment by nicojeske** [comment]
The reason for this bug is possibly located in the screen capturing mechanism. I am currently working on changing some things there in a new version that will likely come later today or tomorrow.

**Comment by ruvaldak** [comment]
New update (2.0.1) fixed accuracy.

**Comment by nicojeske** [comment]
Good to hear that! I will close this issue now.
