### ISSUE TITLE
Still incorrect placement with 2.0.1

### ISSUE THREAD

**Issue by Dj3DX** [nicojeske/RazerAmbilight#23]
On Ambilight 2.0.1 - Windows 10 - RazerOrnata with 22x6 key settings

Sorry to open a new issue but the placement is still wrong. As you can see, the left blue tab and the right green tab both take up the same portion of the screen yet on the keyboard the left one is much bigger while the right is not shown - I assume the right 200 pixels or so of the screen are being cut off. You can also notice the centred icon on my desktop is not on the centre of my keyboard. Right screen is default at 1440p, left is at 1080x1200.
Cheers.

here is the keyboard aligned with the centre of the monitor
![IMG_20190314_194946](https://user-images.githubusercontent.com/25734612/54337157-e4d75e80-4692-11e9-89a4-bac0454abbf7.jpg)

And here is a more standardised view below

![2](https://user-images.githubusercontent.com/25734612/54337178-fde00f80-4692-11e9-9645-f8c15eea3d12.jpg)

**Comment by nicojeske** [comment]
Just out of curiosity. What happens if you set your display resolution of your main monitor to 1080p?

**Comment by Dj3DX** [comment]
Looks like you fixed it with the new .20 version?! Cheers anyways.
