### ISSUE TITLE
Wheel color on Razer Naga chroma

### ISSUE THREAD

**Issue by Yueh72** [nicojeske/RazerAmbilight#24]
Wheel color is always in yellow on Naga Chroma. Even if there is no yellow on screen. It worked well with pre-2.0 versions.

**Comment by nicojeske** [comment]
As i don't own a Naga i once again tested with the [Razer chroma emulator](https://github.com/razerofficial/ChromaEmulator/releases) and the effect works as expected. Please try replug the mouse, restart PC, reinstall Ambilight and as a last try reinstall synapse.

**Comment by nicojeske** [comment]
No answer, so I'll close this issue.
