### ISSUE TITLE
Color Saturation on Mamba TE is really washed out and isn't affected by changing the saturation setting

### ISSUE THREAD

**Issue by AngloNegro** [nicojeske/RazerAmbilight#25]
I hadn't noticed until recently, but on the most recent version the colors on my Mamba TE are very greyed out, and aren't affected by me changing the color saturation. I had to downgrade to 2.0 to get the colors as intense as my keyboard and mousepad.

**Comment by nicojeske** [comment]
Should now be fixed in the current version.

**Comment by AngloNegro** [comment]
> Should now be fixed in the current version.

Looks great! Thank you so much.
