### ISSUE TITLE
Software update proposal

### ISSUE THREAD

**Issue by Felipefuji** [nicojeske/RazerAmbilight#32]
Hello @nicojeske, today I found the project, and after seeing that it has not been updated for a year. I would like to propose you to continue with what you left.
It seems to me a great project and that could be improved, I have many devices that use razer Chroma and I would like them to be supported by this software.

**Comment by nicojeske** [comment]
Hi @Felipefuji thank you for your kind words regarding the Project.
I will soon start looking into the project again and hope to be able to add support for new Devices and more :)

**Comment by Felipefuji** [comment]
I would like to help you as much as possible, even with the certification of the project so that it does not come out as a dangerous application.

**Comment by nicojeske** [comment]
Could you update to 2.4.0, test your devices and list the ones not working?

I will then try to look into these devices specifically, maybe I am able to add support for them rather easily. :)

**Comment by Felipefuji** [comment]
Yes, tomorrow I will add the complete list of what does not work. Although I have also been doing some research to see how I can be of help. Thank you :)

**Comment by Felipefuji** [comment]
Excuse me, my work has kept me pretty busy. Devices that do not work with the current version are:
-Goliathus extended chroma
-base station chroma
-Razer Nari.

I also have all the PC linked to Razer Connect and a Philips Hue led strip connected to Razer Connect.
That doesn't work with the current version either.

**Comment by nicojeske** [comment]
I've updated the software to Version 3.0 and changed to a pre-release version of the part which communicates with your Razer devices.

At least the Razer Nari should now work. I would appreciate it, if you could update and test with your devices.

**Comment by Felipefuji** [comment]
Ok, I'll do the tests this afternoon and give you more information. Thank you so much :)

**Comment by Felipefuji** [comment]
Hello I have already been able to carry out the tests, all the devices work (Philips hue, chroma station, razer, nari and goliathus extender), the only thing that cannot be detected are the rgb components of the pc, I do not know why. There are some things that I think could be improved such as multi-monitor support if possible, and the position of the different devices. But for the rest, I'm really happy.

**Comment by nicojeske** [comment]
Nice to hear that nearly all devices work as expected. As for the RGB Components of your PC I think it is not the fault of the software that those do not work as the RGB Components should work (if they work with Chroma Link) the same as your other chroma link devices, such as Philips Hue and chroma station.

I will open two separate Issues for the multi-monitor support and the position of different devices, but I do not think that I will have time to implement these features right now. Although I will add them to my personal backlog.

I will close this issue for now.

**Comment by Felipefuji** [comment]
The other devices do not work because in the last update of razer synapse 3 it has a bug that makes those devices not work with chroma connect. But in an older version of Razer synapse 3 everything works fine. Thank you :)
